In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
df = pd.read_csv('/content/Zudio_Synthetic_Sales_10K (1).csv')
df.head()

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Store,Product_Category,Items,Unit_Price,...,Gross_Amount,Sales_Amount,Profit,Sales_Channel,Payment_Mode,Hour,Day,Month,Month_Number,Year
0,ZD106605,01-01-2025,CUST101465,Female,23,Hyderabad,Zudio Hyderabad,Women,3,2354,...,7062,6002.70,1957.05,Store,UPI,11,Wednesday,January,1,2025
1,ZD100756,01-01-2025,CUST100252,Male,27,Mumbai,Zudio Mumbai,Men,5,1035,...,5175,4398.75,1012.08,Store,Card,12,Wednesday,January,1,2025
2,ZD109685,01-01-2025,CUST101822,Male,16,Bangalore,Zudio Bangalore,Beauty,5,570,...,2850,2565.00,910.93,Store,UPI,12,Wednesday,January,1,2025
3,ZD103072,01-01-2025,CUST102129,Female,28,Hyderabad,Zudio Hyderabad,Beauty,3,264,...,792,752.40,268.41,Store,UPI,14,Wednesday,January,1,2025
4,ZD100447,01-01-2025,CUST100969,Female,22,Hyderabad,Zudio Hyderabad,Kids,5,585,...,2925,2632.50,826.37,Store,Card,15,Wednesday,January,1,2025

In [ ]:
df.shape

(10000, 21)

In [ ]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Gender', 'Age', 'City',
       'Store', 'Product_Category', 'Items', 'Unit_Price', 'Discount_Percent',
       'Gross_Amount', 'Sales_Amount', 'Profit', 'Sales_Channel',
       'Payment_Mode', 'Hour', 'Day', 'Month', 'Month_Number', 'Year'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          10000 non-null  object
 1   Order_Date        10000 non-null  object
 2   Customer_ID       10000 non-null  object
 3   Gender            10000 non-null  object
 4   Age               10000 non-null  int64
 5   City              10000 non-null  object
 6   Store             10000 non-null  object
 7   Product_Category  10000 non-null  object
 8   Items             10000 non-null  int64
 9   Unit_Price        10000 non-null  int64
 10  Discount_Percent  10000 non-null  int64
 11  Gross_Amount      10000 non-null  int64
 12  Sales_Amount      10000 non-null  float64
 13  Profit            10000 non-null  float64
 14  Sales_Channel     10000 non-null  object
 15  Payment_Mode      10000 non-null  object
 16  Hour              10000 non-null  int64
 17  Day               10000 non-null  object
 18  Month             10000 non-null  object
 19  Month_Number      10000 non-null  int64
 20  Year              10000 non-null  int64
dtypes: float64(2), int64(8), object(11)
memory usage: 1.6+ MB

In [ ]:
df.describe()

,Age,Items,Unit_Price,Discount_Percent,Gross_Amount,Sales_Amount,Profit,Hour,Month_Number,Year
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0
mean,28.292400,2.596300,1138.507300,11.865500,2952.363200,2601.027300,833.708791,17.020100,6.506700,2025.0
std,7.468325,1.321174,609.664655,8.586022,2327.307445,2077.531604,655.343861,3.024336,3.444611,0.0
min,16.000000,1.000000,99.000000,0.000000,102.000000,88.000000,32.440000,9.000000,1.000000,2025.0
25%,23.000000,2.000000,638.000000,5.000000,1233.000000,1076.550000,352.372500,15.000000,4.000000,2025.0
50%,28.000000,2.000000,1038.000000,10.000000,2252.500000,1983.950000,646.030000,17.000000,6.000000,2025.0
75%,33.000000,3.000000,1586.250000,20.000000,4048.500000,3544.800000,1124.707500,19.000000,10.000000,2025.0
max,56.000000,6.000000,2499.000000,30.000000,14922.000000,14628.000000,5357.730000,22.000000,12.000000,2025.0

In [ ]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'],dayfirst=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          10000 non-null  object
 1   Order_Date        10000 non-null  datetime64[ns]
 2   Customer_ID       10000 non-null  object
 3   Gender            10000 non-null  object
 4   Age               10000 non-null  int64
 5   City              10000 non-null  object
 6   Store             10000 non-null  object
 7   Product_Category  10000 non-null  object
 8   Items             10000 non-null  int64
 9   Unit_Price        10000 non-null  int64
 10  Discount_Percent  10000 non-null  int64
 11  Gross_Amount      10000 non-null  int64
 12  Sales_Amount      10000 non-null  float64
 13  Profit            10000 non-null  float64
 14  Sales_Channel     10000 non-null  object
 15  Payment_Mode      10000 non-null  object
 16  Hour              10000 non-null  int64
 17  Day               10000 non-null  object
 18  Month             10000 non-null  object
 19  Month_Number      10000 non-null  int64
 20  Year              10000 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(8), object(10)
memory usage: 1.6+ MB

In [ ]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Gender              0
Age                 0
City                0
Store               0
Product_Category    0
Items               0
Unit_Price          0
Discount_Percent    0
Gross_Amount        0
Sales_Amount        0
Profit              0
Sales_Channel       0
Payment_Mode        0
Hour                0
Day                 0
Month               0
Month_Number        0
Year                0
dtype: int64

In [ ]:
df["Month"]=df['Order_Date'].dt.strftime("%b")
df.head()
#df["Month_Number"]=df['Order_Date'].dt.Month

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Store,Product_Category,Items,Unit_Price,...,Gross_Amount,Sales_Amount,Profit,Sales_Channel,Payment_Mode,Hour,Day,Month,Month_Number,Year
0,ZD106605,2025-01-01,CUST101465,Female,23,Hyderabad,Zudio Hyderabad,Women,3,2354,...,7062,6002.70,1957.05,Store,UPI,11,Wednesday,Jan,1,2025
1,ZD100756,2025-01-01,CUST100252,Male,27,Mumbai,Zudio Mumbai,Men,5,1035,...,5175,4398.75,1012.08,Store,Card,12,Wednesday,Jan,1,2025
2,ZD109685,2025-01-01,CUST101822,Male,16,Bangalore,Zudio Bangalore,Beauty,5,570,...,2850,2565.00,910.93,Store,UPI,12,Wednesday,Jan,1,2025
3,ZD103072,2025-01-01,CUST102129,Female,28,Hyderabad,Zudio Hyderabad,Beauty,3,264,...,792,752.40,268.41,Store,UPI,14,Wednesday,Jan,1,2025
4,ZD100447,2025-01-01,CUST100969,Female,22,Hyderabad,Zudio Hyderabad,Kids,5,585,...,2925,2632.50,826.37,Store,Card,15,Wednesday,Jan,1,2025

In [ ]:
df["Day"]=df["Order_Date"].dt.day_name().str[0:3]
df.sample(5)

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Store,Product_Category,Items,Unit_Price,...,Gross_Amount,Sales_Amount,Profit,Sales_Channel,Payment_Mode,Hour,Day,Month,Month_Number,Year
8833,ZD100358,2025-11-19,CUST100491,Male,28,Pune,Zudio Pune,Kids,2,1043,...,2086,1773.1,562.85,Store,UPI,17,Wed,Nov,11,2025
4845,ZD102992,2025-06-25,CUST101049,Male,20,Chennai,Zudio Chennai,Women,1,2048,...,2048,1843.2,591.51,Store,UPI,15,Wed,Jun,6,2025
7201,ZD108898,2025-09-21,CUST101315,Male,34,Delhi,Zudio Delhi,Men,1,951,...,951,951.0,264.33,Online,UPI,15,Sun,Sep,9,2025
3674,ZD103028,2025-05-14,CUST103756,Female,31,Mumbai,Zudio Mumbai,Kids,1,848,...,848,805.6,258.68,Store,Cash,18,Wed,May,5,2025
3366,ZD107887,2025-05-03,CUST101212,Male,35,Chennai,Zudio Chennai,Women,1,2069,...,2069,1448.3,470.45,Store,UPI,17,Sat,May,5,2025

In [ ]:
monthly_sales=(
    df.groupby(['Month_Number',"Month"])['Sales_Amount'].sum().reset_index().sort_values(by="Month_Number")
)
monthly_sales

    Month_Number Month  Sales_Amount
0              1   Jan    2263341.60
1              2   Feb    1872577.20
2              3   Mar    2196891.35
3              4   Apr    2207270.75
4              5   May    2316828.25
5              6   Jun    2252047.20
6              7   Jul    2135590.95
7              8   Aug    2169985.10
8              9   Sep    2011559.90
9             10   Oct    2113529.10
10            11   Nov    2217399.90
11            12   Dec    2253251.70

In [ ]:

fig=px.line(
    monthly_sales,
    x="Month",
    y="Sales_Amount",
    markers=True,
    template="plotly_dark",
    title="Monthly Sales"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales(Rs.)",
    template="plotly_white"
)

fig.show()

In [ ]:
fig=px.area(
     monthly_sales,
    x="Month",
    y="Sales_Amount",
    markers=True,
    template="plotly_dark",
    title="Monthly Sales"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales(Rs.)",
    template="plotly_white"
)

fig.show()

In [ ]:
category_sales=(
    df.groupby("Product_Category")["Sales_Amount"].sum().reset_index()
     .sort_values(by="Sales_Amount",ascending=False)
)
category_sales

  Product_Category  Sales_Amount
4            Women   11159420.65
3              Men    8739063.30
2             Kids    3623691.45
1           Beauty    1363568.80
0      Accessories    1124528.80

In [ ]:

fig=px.bar(
    category_sales,
    x="Product_Category",
    y="Sales_Amount",
    title="Category Sales",
    template="plotly_white",
    text_auto='.2s',
)

fig.update_layout(
    xaxis_title="Category",
    yaxis_title="Sales(Rs.)",
    template="plotly_white"
)

fig.show()

In [ ]:
city_sales=(
    df.groupby("City")["Sales_Amount"].sum().reset_index().nlargest(5,"Sales_Amount")
     .sort_values(by="Sales_Amount",ascending=False)
)
city_sales

        City  Sales_Amount
3      Delhi    4084383.90
8     Mumbai    3680235.15
1  Bangalore    3112597.40
4  Hyderabad    2779489.65
5     Jaipur    2570721.05

In [ ]:
fig = px.pie(
    city_sales,
    names="City",
    values="Sales_Amount",
    title="Top 5 cities by Sales",
    hole=0.5,
    template="plotly_white"
)
fig.update_traces(textinfo="percent+label")
fig.update_layout(title_x=0.5)

fig.show()

In [ ]:
top_stores = (
    df.groupby("Store",
               as_index=False)["Sales_Amount"].sum().nlargest(5,"Sales_Amount")
               .sort_values(by="Sales_Amount",ascending=False)
)

In [ ]:
fig = px.bar(
    top_stores,
    x = "Store",
    y = "Sales_Amount",
    title = "Top 5 Stores by Sales",
    template = "plotly_white",
    text = "Sales_Amount"
)
fig.update_layout(
    xaxis_title="Store",
    yaxis_title="Sales(Rs.)",
    title_x=0.5
    )

fig.show()

In [ ]:
heatmap_data=(
    df.groupby(['Day','Hour'])["Sales_Amount"].sum().reset_index()
)
heatmap_pivot=heatmap_data.pivot(
    index="Day",
    columns="Hour",
    values="Sales_Amount"
)

heatmap_pivot

Hour,9,10,11,12,13,14,15,16,17,18,19,20,21,22
Day,,,,,,,,,,,,,,
Fri,43453.95,54068.60,73363.15,142105.10,205201.10,222984.65,324424.60,363122.15,473823.70,497145.15,393186.80,423220.55,235651.85,174513.35
Mon,23381.00,32641.90,79363.60,175701.40,182458.80,257391.60,287431.85,400096.70,519030.00,412679.55,368827.60,486959.75,334975.75,196157.15
Sat,58017.45,48154.70,79799.20,155714.20,164878.95,234532.40,262231.00,425775.85,496782.00,452457.05,391934.90,346908.70,302011.45,142755.65
Sun,39241.80,15742.40,94452.10,123864.00,243016.50,193871.35,289309.80,423199.00,514484.70,453354.55,397226.25,377038.05,299455.85,206038.15
Thu,46169.60,62634.35,77150.80,159553.90,181568.05,308020.00,299085.65,402858.25,608869.35,440967.85,296523.25,365508.15,336476.60,198390.85
Tue,40956.75,45793.40,120552.10,171803.70,166764.15,217085.10,305985.80,425214.75,444198.80,533299.40,416693.45,417031.75,319535.35,185243.75
Wed,55185.85,52691.85,123042.25,117968.75,182584.85,222297.90,418153.70,368118.70,472221.00,438780.95,516713.75,404353.75,254662.45,173953.00

In [ ]:
day_order=[
    "Mon","Tue","Wed","Thu","Fri","Sat","Sun"
]

heatmap_pivot=heatmap_pivot.reindex(day_order)
heatmap_pivot

Hour,9,10,11,12,13,14,15,16,17,18,19,20,21,22
Day,,,,,,,,,,,,,,
Mon,23381.00,32641.90,79363.60,175701.40,182458.80,257391.60,287431.85,400096.70,519030.00,412679.55,368827.60,486959.75,334975.75,196157.15
Tue,40956.75,45793.40,120552.10,171803.70,166764.15,217085.10,305985.80,425214.75,444198.80,533299.40,416693.45,417031.75,319535.35,185243.75
Wed,55185.85,52691.85,123042.25,117968.75,182584.85,222297.90,418153.70,368118.70,472221.00,438780.95,516713.75,404353.75,254662.45,173953.00
Thu,46169.60,62634.35,77150.80,159553.90,181568.05,308020.00,299085.65,402858.25,608869.35,440967.85,296523.25,365508.15,336476.60,198390.85
Fri,43453.95,54068.60,73363.15,142105.10,205201.10,222984.65,324424.60,363122.15,473823.70,497145.15,393186.80,423220.55,235651.85,174513.35
Sat,58017.45,48154.70,79799.20,155714.20,164878.95,234532.40,262231.00,425775.85,496782.00,452457.05,391934.90,346908.70,302011.45,142755.65
Sun,39241.80,15742.40,94452.10,123864.00,243016.50,193871.35,289309.80,423199.00,514484.70,453354.55,397226.25,377038.05,299455.85,206038.15

In [ ]:
fig= go.Figure(
    data = go.Heatmap(
        z=heatmap_pivot.values,
        x=heatmap_pivot.columns,
        y=heatmap_pivot.index,
        colorscale="Viridis"
    )
)

fig.update_layout(
    title="Sales by Day and Hour",
    xaxis_title="Hour",
    yaxis_title="Day"
)
fig.show()

In [ ]:
total_sales=df["Sales_Amount"].sum()
print(f"Total Sales: ₹{total_sales:,.0f}")

Total Sales: ₹26,010,273

In [ ]:
total_orders=df["Order_ID"].nunique()
print(f"Total Orders:{total_orders:,}")

Total Orders:10,000

In [ ]:
total_customers=df["Customer_ID"].nunique()
print(f"Total Customers:{total_customers:,}")

Total Customers:3,696

In [ ]:
total_items_sold = df["Items"].sum()
print(f"Total Items Sold:{total_items_sold:,}")

Total Items Sold:25,963

In [ ]:
aov=total_sales/total_orders
print(f"Average Order Value:₹{aov:,.0f}")

Average Order Value:₹2,601

In [ ]:
df['Day_Type'] = df['Order_Date'].dt.dayofweek.apply(lambda x: 'Weekend'if x>= 5 else ' Weekday')

In [ ]:
df[['Order_Date','Day_Type']].head()

  Order_Date  Day_Type
0 2025-01-01   Weekday
1 2025-01-01   Weekday
2 2025-01-01   Weekday
3 2025-01-01   Weekday
4 2025-01-01   Weekday

In [ ]:
top_category = (df.groupby("Product_Category")["Sales_Amount"].sum().idxmax()
)
top_category

'Women'

In [ ]:
best_day = df.groupby("Day")["Sales_Amount"].sum().idxmax()
best_day_sales = df.groupby("Day")["Sales_Amount"].sum().max()

peak_hour = df.groupby("Hour")["Sales_Amount"].sum().idxmax()
peak_hour_sales = df.groupby("Hour")["Sales_Amount"].sum().max()

print("Best Day:",best_day)
print("Best Day Sales:", best_day_sales)

print("Peak Hour:", peak_hour)
print("Peak Hour Sales:", peak_hour_sales)

Best Day: Tue
Best Day Sales: 3810158.25
Peak Hour: 17
Peak Hour Sales: 3529409.55